# Generated by Django 5.1.3 on 2024-12-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wardrobe_assistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outfit",
            name="color",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="outfit",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
